
baseURL = "/"
languageCode = "bn"
title = "Bengali & Arabic Articles"
theme = "PaperMod"

[params]
    defaultTheme = "light"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    ShowToc = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
